/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuRota.java
 *
 * Created on 20/10/2011, 20:38:09
 */
package br.edu.ufcg.dsc.gui;

import java.sql.SQLException;
import java.sql.Time;
import java.util.List;


import javax.swing.JOptionPane;

import br.edu.ufcg.dsc.bean.Empresa;
import br.edu.ufcg.dsc.bean.Horario;
import br.edu.ufcg.dsc.bean.PontoDeRota;

import br.edu.ufcg.dsc.bean.Rota;
import br.edu.ufcg.dsc.facade.BusaoAdministradorFacade;

/**
 *
 * @author Anderson
 */
public class MenuRota extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 8665796919082491914L;
	private BusaoAdministradorFacade facade;
	/** Creates new form MenuRota 
	 * @throws SQLException */
    public MenuRota() throws SQLException {
    	facade = new BusaoAdministradorFacade();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        onibus = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        empresa = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        horaInicio = new javax.swing.JComboBox();
        horaFinal = new javax.swing.JComboBox();
        minutoFinal = new javax.swing.JComboBox();
        minutoInicio = new javax.swing.JComboBox();
        numDestino = new javax.swing.JTextField();
        via = new javax.swing.JTextField();
        cor = new javax.swing.JTextField();
        link = new javax.swing.JTextField();
        intervalo = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numeracao de Destino");

        jLabel2.setText("Via");

        jLabel3.setText("Cor");

        jLabel4.setText("Link GMaps");

        try {
			onibus.setModel(new javax.swing.AbstractListModel() {
				private static final long serialVersionUID = 1273779180069016638L;
				Object[] buses = facade.getOnibus().toArray();
			    public int getSize() {return buses.length;}
			    public Object getElementAt(int i){return buses[i];}
			});
		} catch (SQLException e) {
			 JOptionPane.showMessageDialog(null, e.getMessage(),
		                "Busca sem sucesso",
		                JOptionPane.ERROR_MESSAGE);
		}
        onibus.setToolTipText("Selecione um ou mais onibus que irao pertencer a rota.");
        jScrollPane1.setViewportView(onibus);

        try {
			empresa.setModel(new javax.swing.AbstractListModel() {
				private static final long serialVersionUID = 1273779180069016638L;
				Object[] empresas = facade.getEmpresas().toArray();
			    public int getSize() {return empresas.length;}
			    public Object getElementAt(int i){return empresas[i];}
			});
		} catch (SQLException e) {
			 JOptionPane.showMessageDialog(null, e.getMessage(),
		                "Busca sem sucesso",
		                JOptionPane.ERROR_MESSAGE);
		}
        empresa.setToolTipText("Seleione a sua empresa.");
        jScrollPane2.setViewportView(empresa);

        jLabel5.setText("Onibus pertencentes a rota");

        jLabel6.setText("Empresa");

        jLabel7.setText("Hora inicial da rota");

        jLabel8.setText("Hora final da rota");

        jLabel9.setText("Intervalo entre onibus (em minutos)");
        
        voltar.setIcon(new javax.swing.ImageIcon("/br/edu/ufcg/dsc/gui/images/1317175785_back.png")); // NOI18N
        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/dsc/gui/images/1317256235_add1-.png"))); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        horaInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23" }));
        horaInicio.setToolTipText("Escolha a hora inicial da rota.");

        horaFinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23" }));
        horaFinal.setToolTipText("Escolha a hora final da rota");

        minutoFinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        minutoInicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        numDestino.setToolTipText("Digite um identificador no formato \"999\" ou \"999-A\", por exemplo.");

        via.setToolTipText("Esse campo e opcional. Preencha apenas se a rota possui duas linhas, \"A\" e \"B\".");

        cor.setToolTipText("Preencha com a cor correspondente a rota. Exemplo: \"Laranja\".");
        cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corActionPerformed(evt);
            }
        });

        link.setText("http://tinyurl.com/3ds6kmj");
        link.setToolTipText("Para preencher esse campo, acesse este link: \nhttp://maps.google.com.br/  \nLocalize a cidade de sua empresa e desenhe a rota correspondente.\nPara ver um exemplo, copie e cole o link no seu navegador.");
        link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkActionPerformed(evt);
            }
        });

        intervalo.setToolTipText("Preencha com o intervalo, em minutos, entre os onibus desta rota.");

        
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(via, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(minutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voltar)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(horaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(minutoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cadastrar)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(via, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltar)
                            .addComponent(cadastrar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
    String id = numDestino.getText();
    String cor = this.cor.getText();
    String link = this.link.getText();
    String via = this.via.getText();
    List<String> pontos = facade.extraiPontos(link);
    addPontosRota(pontos,id);
    int horaInicial = Integer.parseInt(horaInicio.getSelectedItem().toString());
    int minutoInicial = Integer.parseInt(minutoInicio.getSelectedItem().toString());
    
    int horaFinal = Integer.parseInt(this.horaFinal.getSelectedItem().toString());
    int minutoFinal = Integer.parseInt(this.minutoFinal.getSelectedItem().toString());
    
    int intervalo = Integer.parseInt(this.intervalo.getText());
    
    Empresa enterprise = (Empresa) empresa.getSelectedValue();
    Object[] onibus = this.onibus.getSelectedValues();
    int qtdeOnibus = 0;
  for(int i = 0;i < onibus.length; i ++){
  	qtdeOnibus++;
  }
    int tempoInicial = ((horaInicial * 60) + minutoInicial) * 1000;
    int tempoFinal = ((horaFinal * 60) + minutoFinal) * 1000;
    int tempoTotal = (tempoFinal - tempoInicial)/1000;
    Time tInicio = new Time(System.currentTimeMillis() + tempoInicial);
    Time tFim = new Time(System.currentTimeMillis() + tempoFinal);
    try {
		facade.cadastrarRota(new Rota(id,cor,0,new Horario(intervalo, tempoTotal, tInicio, tFim),enterprise.getIdentificador(),link,qtdeOnibus,via));
		JOptionPane.showMessageDialog(null, "A rota foi adicionada com sucesso!");
	} catch (SQLException e) {
		 JOptionPane.showMessageDialog(null, e.getMessage(),
	             "Nao foi possivel adicionar a rota",
	             JOptionPane.ERROR_MESSAGE);
		 e.printStackTrace();
	}
	MainMenuRota m = new MainMenuRota();
	m.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	m.setVisible(true);
	dispose();

}//GEN-LAST:event_cadastrarActionPerformed

private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
MainMenuRota m = new MainMenuRota();
m.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
m.setVisible(true);
dispose();
}//GEN-LAST:event_voltarActionPerformed

private void corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corActionPerformed

}//GEN-LAST:event_corActionPerformed

private void linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkActionPerformed

}//GEN-LAST:event_linkActionPerformed

private void addPontosRota(List<String> pontos, String idRota){
	PontoDeRota ponto = null;
	String[] pontoTemp = new String[2];
	for (int i = 0; i < pontos.size(); i++) {
		pontoTemp = pontos.get(i).split(",");
		ponto = new PontoDeRota(0,Double.parseDouble(pontoTemp[1]),Double.parseDouble(pontoTemp[0]),idRota);
		try {
			facade.addPontoRota(ponto);
		} catch (SQLException e) {
			 JOptionPane.showMessageDialog(null, e.getMessage(),
		             "Erro ao adicionar um ponto na rota",
		             JOptionPane.ERROR_MESSAGE);
		}
	}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
					new MenuRota().setVisible(true);
				} catch (SQLException e) {
					 JOptionPane.showMessageDialog(null, e.getMessage(),
				                "Busca sem sucesso",
				                JOptionPane.ERROR_MESSAGE);
				}
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField cor;
    private javax.swing.JList empresa;
    private javax.swing.JComboBox horaFinal;
    private javax.swing.JComboBox horaInicio;
    private javax.swing.JTextField intervalo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField link;
    private javax.swing.JComboBox minutoFinal;
    private javax.swing.JComboBox minutoInicio;
    private javax.swing.JTextField numDestino;
    private javax.swing.JList onibus;
    private javax.swing.JTextField via;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
