/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAdministrador.java
 *
 * Created on 27/09/2011, 22:26:41
 */
package br.edu.ufcg.dsc.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Leite
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /** Creates new form MenuAdministrador */
    public MenuAdministrador() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cidadeButton = new javax.swing.JButton();
        rotaButton = new javax.swing.JButton();
        empresaButton = new javax.swing.JButton();
        onibusButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cidadeButton.setText("Cidade");
        cidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeButtonActionPerformed(evt);
            }
        });

        rotaButton.setText("Rota");
        rotaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotaButtonActionPerformed(evt);
            }
        });

        empresaButton.setText("Empresa");
        empresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaButtonActionPerformed(evt);
            }
        });

        onibusButton.setText("Onibus");
        onibusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onibusButtonActionPerformed(evt);
            }
        });
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/dsc/gui/images/logotipo_principal.png"))); // NOI18N

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/dsc/gui/images/1317174121_door_out.png"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(rotaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(empresaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cidadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(onibusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotaButton)
                    .addComponent(empresaButton))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cidadeButton)
                    .addComponent(onibusButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        
        dispose();
        
        Object[] options2 = { "Sim", "Nao" };
        
        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja sair", null, JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options2, options2[0]); 
        
        if (resposta == 0){
             System.exit(0);
        } else {
            new MenuAdministrador().setVisible(true);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void cidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeButtonActionPerformed
    	MenuCidade cidade = new MenuCidade();
    	cidade.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cidade.setVisible(true);
        dispose();
    }//GEN-LAST:event_cidadeButtonActionPerformed

    private void empresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaButtonActionPerformed
    	MenuEmpresa empresa = new MenuEmpresa();
    	empresa.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        empresa.setVisible(true);
        dispose();
    }//GEN-LAST:event_empresaButtonActionPerformed

    private void rotaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotaButtonActionPerformed
    	MenuRota rota = new MenuRota();
    	rota.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        rota.setVisible(true);
        dispose();
    }//GEN-LAST:event_rotaButtonActionPerformed
    
    private void onibusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotaButtonActionPerformed
    	MenuOnibus onibus = new MenuOnibus();
    	onibus.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        onibus.setVisible(true);
        dispose();
    }//GEN-LAST:event_rotaButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cidadeButton;
    private javax.swing.JButton empresaButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton onibusButton;
    private javax.swing.JButton rotaButton;
    // End of variables declaration//GEN-END:variables
}
