/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuOnibus.java
 *
 * Created on 28/09/2011, 21:44:49
 */
package br.edu.ufcg.dsc.gui;

import br.edu.ufcg.dsc.service.OnibusService;
import br.edu.ufcg.dsc.bean.Cidade;
import br.edu.ufcg.dsc.bean.Onibus;
import br.edu.ufcg.dsc.facade.BusaoAdministradorFacade;
import br.edu.ufcg.dsc.facade.BusaoFacade;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Leite
 */
public class MenuOnibus extends javax.swing.JFrame {
	
	private BusaoAdministradorFacade facade;

    /** Creates new form MenuOnibus 
     * @throws SQLException */
    public MenuOnibus() throws SQLException {
    	
    	facade = new BusaoAdministradorFacade();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException {

        voltarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        identificadorOnibus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        capacidadeOnibus = new javax.swing.JComboBox();
        adicionarOnibusButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        removerOnibusButton = new javax.swing.JButton();
      

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/dsc/gui/images/1317175785_back.png"))); // NOI18N
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Para adicionar um Onibus, por favor preencher campos abaixo.");

        jLabel2.setText("Identificador:");

        jLabel3.setText("Capacidade:");

        capacidadeOnibus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        
        
        adicionarOnibusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/dsc/gui/images/1317256235_add1-.png"))); // NOI18N
        adicionarOnibusButton.setText("Adicionar Onibus");
        adicionarOnibusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarOnibusButtonActionPerformed(evt);
            }
        });
        
      

        jLabel4.setText("Para remover um Onibus, pressione botao abaixo e escolha o Onibus a ser removido.");

        removerOnibusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/dsc/gui/images/1317256312_Delete.png"))); // NOI18N
        removerOnibusButton.setText("Remover Onibus");
        removerOnibusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					removerOnibusButtonActionPerformed(evt);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificadorOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidadeOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(adicionarOnibusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(removerOnibusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(voltarButton)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(identificadorOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(capacidadeOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(adicionarOnibusButton)))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(removerOnibusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        new MenuAdministrador().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void adicionarOnibusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarOnibusButtonActionPerformed
        String identificador = identificadorOnibus.getText();
        int capacidade = Integer.parseInt(capacidadeOnibus.getSelectedItem().toString());
        
        try {
			facade.adicionarOnibus(new Onibus(identificador));
			JOptionPane.showMessageDialog(null, "Onibus adicionado com sucesso");
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Erro na conexao com o banco de dados");
			e.printStackTrace();
		}
        
        dispose();
    }//GEN-LAST:event_adicionarOnibusButtonActionPerformed

    private void removerOnibusButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_removerOnibusButtonActionPerformed
        List<String> onibus = new ArrayList<String>();
        
        for (int i = 0; i < OnibusService.getInstance().getOnibus().size(); i++) {
            onibus.add(OnibusService.getInstance().getOnibus().get(i).getIdentificador());
        }
        
        dispose();
        
        String removeOnibus = (String) JOptionPane.showInputDialog(null,"Escolha o onibus a ser removido:", "Busao Administrador",
			JOptionPane.PLAIN_MESSAGE, null, onibus.toArray(), onibus.toArray()[0]);
        
       facade.removerOnibus(facade.getOnibus(removeOnibus));
        
        JOptionPane.showMessageDialog(null, "Onibus removido com sucesso");
        MenuOnibus bus = new MenuOnibus();
        bus.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        bus.setVisible(true);
      
    }//GEN-LAST:event_removerOnibusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
					new MenuOnibus().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarOnibusButton;
    private javax.swing.JComboBox capacidadeOnibus;
    private javax.swing.JTextField identificadorOnibus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton removerOnibusButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
